sqlplus sdu/AaZZ0r_cle#1@benchadw19_medium

create table POC_TAC (id number GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER
  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  instance_name varchar2(100));

BEGIN
LOOP
	insert into POC_TAC (instance_name) select instance_name from v$instance;
	dbms_session.sleep (2);
	commit;
END LOOP;
END;
/


-- Mientras tanto hago switchover !!!

ERROR at line 1:
ORA-03113: end-of-file on communication channel
Process ID: 129462
Session ID: 48083 Serial number: 26232


=> Normal, porque no he activado el TAC sobre el servicio MEDIUM !!!

BEGIN
	DBMS_CLOUD_ADMIN.ENABLE_APP_CONT(service_name => 'ixcsyvrmtjm8ebr_benchadw19_medium.adwc.oraclecloud.com');
END;
/


[opc@benchcn01 admin]$ sqlplus admin/AaZZ0r_cle#1@benchadw19_medium

SQL*Plus: Release 19.0.0.0.0 - Production on Fri Jul 17 08:34:59 2020
Version 19.6.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

Last Successful login time: Fri Jul 17 2020 08:00:41 +00:00

Connected to:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.5.0.0.0

SQL> 
SQL> 
SQL> BEGIN
	DBMS_CLOUD_ADMIN.ENABLE_APP_CONT(service_name => 'ixcsyvrmtjm8ebr_benchadw19_medium.adwc.oraclecloud.com');
END;
/
  2    3    4  

PL/SQL procedure successfully completed.

SQL> SQL> 
SQL> 
SQL> 

-- Repito la prueba !!!
--

sqlplus sdu/AaZZ0r_cle#1@benchadw19_medium

truncate table POC_TAC;

BEGIN
LOOP
	insert into POC_TAC (instance_name) select instance_name from v$instance;
	dbms_session.sleep (2);
	commit;
END LOOP;
END;
/

ERROR at line 1:
ORA-25403: could not reconnect

=> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

SQL> select instance_name from v$instance;
ERROR:
ORA-03114: not connected to ORACLE

[opc@benchcn01 admin]$ sqlplus sdu/AaZZ0r_cle#1@benchadw19_medium

SQL*Plus: Release 19.0.0.0.0 - Production on Fri Jul 17 08:39:54 2020
Version 19.6.0.0.0

Copyright (c) 1982, 2019, Oracle.  All rights reserved.

ERROR:
ORA-12514: TNS:listener does not currently know of service requested in connect
descriptor















