#!/usr/bin/perl
# #####################################################################
# $Header: LR_4Kst_Residuals.pl 15-feb-2010 sduprat_es Exp $
#
# LR_4Kst_Residuals.pl
#
# Copyright (c) 2010, Oracle Consulting (Spain).  All rights reserved.
#
#    NAME
#     LR_4Kst_Residuals.pl
#
#    DESCRIPTION
#     This perl script is a subroutine: launched by LR_4Kst.pl as part of Residuals Analisis.
#                                       It can be manually launched if necessary
#
#    NOTES
#           Parameters: 
#               Param 1 = LR_4Kst-<Project>-<metric>.dat file, generated by LR_4Kst.pl
#               Param 2 = LR_4Kst-<Project>-<metric>.stats file, generated by LR_4Kst.pl
#               Param 3 = Metric Label (Example: "Logical Reads")
#               Param 4 = Gnuplot Terminal type (Example: GIF)
#               Param 5 = Number of singular pojnts to detect
#
#    MODIFIED        (MM/DD/YY)
#     sduprat_es      15/02/10   - Creation and mastermind
#     sduprat_es      18/02/10   - Output format for GNUPlot managed with 4KST_GNUPLOT_TERM parameter
#     sduprat_es      02/03/10   - Format the Outlier Spotlight Graph (OSG)
#
#    1.2.12      acarrasco_es, sduprat_es      10/02/11   - Singular points automatic detection
#
# #####################################################################
use Switch;
my $LRDatFile;
my $LRStatsFile;
my $LRResidualDatFile;
my $LRResidualGpFile;
my $LRResidualPngFile;
my $LRSingularDatFile;
my $LROSGGpFile;
my $LROSGPngFile;
my $MetricLabel;
my $m;
my $b;

###########
## MAIN ###
###########
$numArgs = $#ARGV + 1;
if ($numArgs > 5 )	{ print "ERROR: to many arguments\nUSAGE: LR_4Kst_Residuals.pl {LR dat file} {LR stats file} {metric label} {GNUPlot term}\n"; exit -1; }
if ($numArgs < 5 )	{ print "ERROR: to few arguments\nUSAGE: LR_4Kst_Residuals.pl {LR dat file} {LR stats file} {metric label} {GNUPlot term}\n"; exit -1; }
if ($numArgs == 5 )	{ $LRDatFile = "$ARGV[0]"; $LRStatsFile="$ARGV[1]"; $MetricLabel="$ARGV[2]"; $gpterm="$ARGV[3]"; $numsing="$ARGV[4]";}

$LRResidualDatFile = $LRDatFile;
$LRResidualDatFile =~ s/\.dat/\_residual\.dat/;
$LRSingularDatFile = $LRDatFile;
$LRSingularDatFile =~ s/\.dat/\_singular\.dat/;
$LRResidualGpFile = $LRDatFile;
$LRResidualGpFile =~ s/\.dat/\_residual\.gp/;
$LRResidualPngFile = $LRDatFile;
$LRResidualPngFile =~ s/\.dat/\_residual\.$gpterm/;

$LROSGGpFile = $LRDatFile;
$LROSGGpFile =~ s/\.dat/\_outlier\.gp/;
$LROSGPngFile = $LRDatFile;
$LROSGPngFile =~ s/\.dat/\_outlier\.$gpterm/;

##
## Primero leemos el fichero de stats (LR_4Kst-<project>-<metric>.stats), para capturar el valor de m,b
## m y b son los coeficientes de Regresion linear calculados por LR_4Kst.pl (f(x) = m*x + b) !!!
##
open ( LR_STATS_FILE, "< $LRStatsFile" ) or die "Can't open $LRStatsFile : $!";
@arr1 = ();
@arr2 = ();
while (<LR_STATS_FILE>)
{
    $line = $_;
    if ($line =~ /^m[ ]*=/)
    {
        chomp($line);
        @arr1 = split(/\s+/, $line);
    }

    if ($line =~ /^b[ ]*=/)
    {
        chomp($line);
        @arr2 = split(/\s+/, $line);
    }

} ## Final lectura de LR_STATS_FILE !!!
close LR_STATS_FILE;

## Esto se queda con los ultimos valores de m y b leidos en el fichero LR_4Kst-<project>-<metric>.stats !!!
$m = @arr1[2];
$b = @arr2[2];

##
## Aqui empieza el analisis de los valores residuales: para cada linea en el fichero LR_4Kst-<project>-<metric>.dat
## el primer valor es el valor de la metrica (x) y el segundo valor es la utilizacion de CPU (y)
## Calculamos el valor residual : Res = (Predicted Value) - (Actual value) = (m*x + b) - y
## Luego generamos la grafica de analisis residual: nube de puntos donde x=(Predicted Value)=(m*x + b) e y=Res !!!
##
open ( LR_DAT_FILE, "< $LRDatFile" ) or die "Can't open $LRDatFile : $!";
open ( LR_RES_DAT_FILE, "> $LRResidualDatFile") or die "Can't open $LRResidualDatFile : $!";
@arr = ();
my $Metric;
my $ActualValue;
my $PredictedValue;
my $Residual;
my $SqResidual; ## Squared residual for Outlier Spotlight Graph !!!
my $cnt;
##
$cnt = 1;
while (<LR_DAT_FILE>)
{
    $line = $_;
    chomp($line);
    @arr = split(/ /, $line);
    ##
    $Metric = @arr[0];
    $ActualValue = @arr[1];
    $snapid = @arr[2];
    $PredictedValue = ( $m * $Metric ) + $b; 
    $Residual = $PredictedValue - $ActualValue;
    $SqResidual = $Residual * $Residual;
    ##
    ## Escritura al fichero de datos residual !!!
    ##
    print LR_RES_DAT_FILE "$PredictedValue $Residual $cnt $SqResidual $Metric $ActualValue $snapid\n";
    $cnt = $cnt + 1;
} ## Final lectura de LR_DAT_FILE !!!
##
close LR_DAT_FILE;
close LR_RES_DAT_FILE;


## 
## Ahora se genera el fichero de puntos singulares !!!
##

`sort -g -r -k4 $LRResidualDatFile | head -$numsing > $LRSingularDatFile`;
##

##
## Por ultimo se genera el programa *.gp de generacion de grafica de los valores residuales !!!
##

open ( LR_GP_FILE, "> $LRResidualGpFile") or die "Can't open $LRResidualGpFile : $!";
print LR_GP_FILE "#!/usr/bin/gnuplot\n";
print LR_GP_FILE "reset\n";
print LR_GP_FILE "set terminal $gpterm\n";
print LR_GP_FILE "set style line 1 lt 1 lc rgb 'black' lw 1\n";
print LR_GP_FILE "set style line 2 lt 2 lc rgb 'gray' lw 0.25\n";
print LR_GP_FILE "set ylabel \"Residual Values (Predicted - Actual)\" textcolor rgb 'blue'\n";
print LR_GP_FILE "set xlabel \"Predicted Values\" textcolor rgb 'blue'\n";
print LR_GP_FILE "set title \"4Kst - Linear Regression by $MetricLabel - Residual Analisis\" textcolor rgb 'blue'\n";
print LR_GP_FILE "set mxtics\nset mytics\nset xtics\nset ytics\nset grid xtics ytics mxtics mytics ls 1, ls 2\n";
print LR_GP_FILE "set key reverse Left bmargin\nset grid\nset style data linespoints\n";
print LR_GP_FILE "plot '$LRResidualDatFile' using 1:2 title 'Residual Analisis'  with points\n";
close (LR_GP_FILE);
`chmod +x $LRResidualGpFile`;
`$LRResidualGpFile > $LRResidualPngFile`;

##
## Added on 02/03/2010: Outlier Spotlight Graph !!!
##
open ( LR_OSG_GP_FILE, "> $LROSGGpFile") or die "Can't open $LROSGGpFile : $!";
print LR_OSG_GP_FILE "#!/usr/bin/gnuplot\n";
print LR_OSG_GP_FILE "reset\n";
print LR_OSG_GP_FILE "set terminal $gpterm\n";
print LR_OSG_GP_FILE "set style line 1 lt 1 lc rgb 'black' lw 1\n";
print LR_OSG_GP_FILE "set style line 2 lt 2 lc rgb 'gray' lw 0.25\n";
print LR_OSG_GP_FILE "set ylabel \"Squared Residual Values\" textcolor rgb 'blue'\n";
print LR_OSG_GP_FILE "set xlabel \"Data Points\" textcolor rgb 'blue'\n";
print LR_OSG_GP_FILE "set title \"4Kst - Linear Regression by $MetricLabel - Outlier Spotlight Graph\" textcolor rgb 'blue'\n";
print LR_OSG_GP_FILE "set mxtics\nset mytics\nset xtics\nset ytics\nset grid xtics ytics mxtics mytics ls 1, ls 2\n";
print LR_OSG_GP_FILE "set key reverse Left bmargin\nset grid\nset style data linespoints\n";
print LR_OSG_GP_FILE "plot \"< sort -g -r -k4 $LRResidualDatFile | cut -f3,4 -d\\\" \\\" \" using 2 title 'Outlier Spotlight Graph'";
close (LR_OSG_GP_FILE);
`chmod +x $LROSGGpFile`;
`$LROSGGpFile > $LROSGPngFile`;

